settings:
  title: 'Status Page'
  url: 'https://status.nekocafe.moe' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: nekocafe-mainsite
    name: NekoCafe
    description: 'NekoCafe Main Site'
    url: 'https://nekocafe.moe'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: buguwu
    name: bugUwU Personal Website
    description: 'bugUwU Personal Website'
    url: 'https://qwq.lgbt'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: catland-bbs
    name: Catland猫猫大陆论坛
    description: 'Catland猫猫大陆官方论坛'
    url: 'https://catland.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: nekocafe-subconverter
    name: SubConverter
    description: 'Utility to convert between various subscription format'
    url: 'https://sub.api.nekocafe.moe'
    method: GET
    expectStatus: 404
    linkable: false # allows the title to be a link, default=true
      
  - id: neteasemusic-api
    name: NeteaseCloudMusic API
    description: '网易云音乐 Node.js API service'
    url: 'https://neteasemusic.api.nekocafe.moe'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: buguwu-chatgpt-bot # unique identifier
    name: buguwuChatGPTBot (Telegram Bot)
    description: 'buguwu ChatGPT Bot For Telegram' # default=empty
    url: 'https://buguwuchatgpt.bot.nekocafe.moe/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
